# .github/workflows/test-health.yml
name: Run Specific Unity Test

on:
  push:
    paths:
      - '**/HealthTest.cs'
  workflow_dispatch:  # allows manual trigger

jobs:
  test:
    name: Run HealthTest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run HealthTest only
        uses: game-ci/unity-test-runner@v3
        with:
          projectPath: .
          testMode: playmode
          testPlatform: StandaloneLinux64
          customParameters: '-runTests -testFilter=HealthTest'
